---
# tasks file for ubuntukibana

- name: Uncomment server.port on Ubuntu
  replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.port.*'
    replace: 'server.port: 5601'

- name: Uncomment server.host on Ubuntu
  replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.host.*'
    replace: 'server.host "localhost"'

- name: Uncomment elasticsearch.hosts on Ubuntu
  replace:
    path: /etc/kibana/kibana.yml
    regexp: '^#elasticsearch.hosts.*'
    replace: 'elasticsearch.hosts: ["http://localhost:9200"]'

- name: Start and Enable Kibana
  service:
    name: kibana
    state: started
    enabled: yes

- name: Allow Kibana TCP Port on Ubuntu
  ufw:
    rule: allow
    port: '5601'
    proto: tcp

- name: Reload UFW and Enable
  ufw:
    state: enabled
